#+Title: Hitu's GNU Emacs Configuration
#+DATE: December 21st, 2025. (Sunday)
#+AUTHOR: G. Hitendra Varma
#+DESCRIPTION: Documentation of my Emacs configuration and packages.
#+STARTUP: overview
#+OPTIONS: toc:2

* Table of Contents :toc:
- [[#package-manager][Package Manager]]
  - [[#packageel-setup][package.el Setup]]
- [[#emacs-customizations][Emacs Customizations]]
  - [[#autosave--backup-files-relocation][Autosave & Backup Files Relocation]]
  - [[#default-coding-system][Default Coding System]]
  - [[#fonts][Fonts]]
  - [[#org-mode-workflow][org-mode Workflow]]
- [[#packages][Packages]]
  - [[#magit][Magit]]
  - [[#which-key][which-key]]
  - [[#toc-org][toc-org]]
  - [[#org-bullets][org-bullets]]
  - [[#emmet][Emmet]]
  - [[#org-roam][org-roam]]
- [[#built-in-packages][Built-In Packages]]
  - [[#org-indent-mode][org-indent-mode]]
  - [[#prettify-symbols-mode][prettify-symbols-mode]]
  - [[#delete-selection-mode][delete-selection-mode]]
  - [[#whitespace-mode][whitespace-mode]]
    - [[#work-in-progress-find-proper-colors-that-work-well-with-the-theme][WORK-IN-PROGRESS Find proper colors that work well with the theme.]]
- [[#theming][Theming]]
  - [[#org-mode][org-mode]]
  - [[#splash-screen][Splash screen]]

* Package Manager

Just using the build-in Emacs package manager (package.el)
Might update to elpaca, straight.el, or use-package in the future.

** package.el Setup

#+begin_src emacs-lisp

  (require 'package)

  (setq package-archives
        '(("gnu" . "https://elpa.gnu.org/packages/")
  	("melpa" . "https://melpa.org/packages/")))

  (package-initialize)

  (unless package-archive-contents
    (package-refresh-contents))

#+end_src

* Emacs Customizations

** Autosave & Backup Files Relocation

Moving the annoying backup and autosave files that Emacs creates right beside the source file
to Emacs' configuration directory.
(Change the path to your preferred location)

#+begin_src emacs-lisp

  ;; Save all backup files in one place
  (setq backup-directory-alist
        '(("." . "~/.emacs.d/backups")))

  ;; Save all auto-save files in one place
  (setq auto-save-file-name-transforms
        '((".*" "~/.emacs.d/auto-saves/" t)))

  ;; Bug fixes
  (setq backup-by-copying t)     ;; don't clobber symlinks
  (setq delete-old-versions t)   ;; clean up excess backups
  (setq kept-new-versions 6)     ;; keep 6 most recent backups
  (setq kept-old-versions 2)     ;; keep two very old backups
  (setq version-control t)       ;; use numbered backups

#+end_src

** Default Coding System

I wanted UTF-8 to be my default enconding, since I regularly use foreign language scripts.
(Emacs should already default to unicode, but feel free to remove this if you only use English)

#+begin_src emacs-lisp

  (set-language-environment "UTF-8")
  (prefer-coding-system 'utf-8-unix)

#+end_src

** Fonts

(Add your preferred fonts, but I do highly recommend "Martin Mono")

#+begin_src emacs-lisp

  ;; Default font
  (set-face-attribute 'default nil
  		    :font "Martian Mono Nerd Font"
  		    :height 120
  		    :weight 'regular)

  ;; Font to be used during non-monospace contexts
  (set-face-attribute 'variable-pitch nil
  		    :font "Ubuntu"
  		    :height 120
  		    :weight 'medium)

  ;; Make sure new frames get it too
  (add-to-list 'default-frame-alist
  	     '(font . "Martian Mono Nerd Font-12"))

  ;; For Telugu script writing
  (set-fontset-font t 'telugu "Noto Sans Telugu")

  ;; Line Spacing
  (setq-default line-spacing 0.12)

#+end_src

** org-mode Workflow

Inspired by the Kanban style project management.

#+begin_src emacs-lisp

  (setq org-todo-keywords
        '(("TODO" "IDEA" "RESEARCH" "WORK-IN-PROGRESS" "|" "DONE" "DROPPED")))

#+end_src

* Packages

** Magit

#+begin_src emacs-lisp

  (unless (package-installed-p 'magit)
    (package-install 'magit))

  ;; Magit configuration
  (global-set-key (kbd "C-x g") #'magit-status)

  (setq magit-display-buffer-function
        #'magit-display-buffer-same-window-except-diff-v1)

#+end_src

** which-key

#+begin_src emacs-lisp

  (unless (package-installed-p 'which-key)
    (pakage-install 'which-key))

  (with-eval-after-load 'which-key
    (setq which-key-side-window-location 'bottom
  	which-key-sort-order #'which-key-key-order-alpha
  	which-key-sort-uppercase-first nil
  	which-key-add-column-padding 1
  	which-key-max-display-columns nil
  	which-key-min-display-lines 6
  	whick-key-side-window-slot -10
  	which-key-side-window-max-height 0.25
  	which-key-idle-delay 0.8
  	which-key-max-description-length 25
  	which-key-allow-imprecise-window-fit t
  	which-key-seperator "~~❥"))

  (which-key-mode 1)

#+end_src

** toc-org

#+begin_src emacs-lisp

  (unless (package-installed-p 'toc-org)
    (package-install 'toc-org))

  (with-eval-after-load 'toc-org
    (setq toc-org-max-depth 3))

  (add-hook 'org-mode-hook #'toc-org-mode)

#+end_src

** org-bullets

#+begin_src emacs-lisp

  (unless (package-installed-p 'org-bullets)
    (package-install 'org-bullets))

  (with-eval-after-load 'org-bullets
    (setq org-bullets-bullet-list '("✬" "ꕥ" "▶" "╰┈➤")))

  (add-hook 'org-mode-hook #'org-bullets-mode)

#+end_src


** Emmet

*C-j* is the default keybind, which is what I'm using here.

#+begin_src emacs-lisp

  (unless (package-installed-p 'emmet-mode)
    (package-refresh-contents)
    (package-install 'emmet-mode))

  (require 'emmet-mode)

  (add-hook 'html-mode-hook #' emmet-mode)
  (add-hook 'css-mode-hook  #' emmet-mode)
  (add-hook 'web-mode-hook  #' emmet-mode)

#+end_src

** org-roam

#+begin_src emacs-lisp

  (unless (package-installed-p 'org-roam)
    (package-refresh-contents)
    (package-install 'org-roam))

  (require 'org-roam)

  ;; Basic Configuration
  (setq org-roam-directory
        (file-truename "~/Documents/RoamNotes/"))

  ;; Key Bindings
  (global-set-key (kbd "C-c n l") #'org-roam-buffer-toggle)
  (global-set-key (kbd "C-c n f") #'org-roam-node-find)
  (global-set-key (kbd "C-c n g") #'org-roam-graph)
  (global-set-key (kbd "C-c n i") #'org-roam-node-insert)
  (global-set-key (kbd "C-c n c") #'org-roam-node-capture)

  (global-set-key (kbd "C-c n j") #'org-roam-dailies-capture-today)

  ;; Template
  (setq org-roam-node-display-template
        (concat "${title:*} "
    	      (propertize "${tags: 10}" 'face 'org-tag)))

  ;; Enable automatic database updates
  (org-roam-db-autosync-mode 1)

  ;; Optional: org-roam-protocol
  (require 'org-roam-protocol)

#+end_src

* Built-In Packages

** org-indent-mode

#+begin_src emacs-lisp

  (setq org-indent-indentation-per-level 2)

  (add-hook 'org-mode-hook #'org-indent-mode)

#+end_src

** prettify-symbols-mode

#+begin_src emacs-lisp

  (global-prettify-symbols-mode 1)

#+end_src

** delete-selection-mode

#+begin_src emacs-lisp

  (delete-selection-mode 1)

#+end_src

** whitespace-mode

*** WORK-IN-PROGRESS Find proper colors that work well with the theme.

#+begin_src emacs-lisp

  ;; (global-whitespace-mode 1)

  ;; (setq whitespace-style
  ;;      '(face trailing tabs tab-mark))

  ;; (set-face-attribute 'whitespace-tab nil
  ;; 		    :background nil
  ;; 		    :foreground "#888888")

#+end_src

* Theming

#+begin_src emacs-lisp

  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)

  ;; Padding
  ;;(setq-default
  ;; left-margin-width 2
  ;; right-margin-width 2)

  ;;(setq-default header-line-format
  ;;	      '(:eval (propertize " " 'display '(height 1.7))))

  ;;(defun my/apply-window-margins ()
  ;;  (set-window-margins (selected-window)
  ;;		      left-margin-width
  ;;		      right-margin-width))

  ;;(add-hook 'window-configuration-change-hood #'my/apply-window-margins)

  ;;(add-to-list 'default-frame-alist '(internal-border-width . 0))
  ;;(set-frame-parameter nil 'internal-border-width 0)

  ;; Disabling margins for Magit
  ;;(add-hook 'magit-mode-hook
  ;;	  (lambda () (set-window-margins (selected-window) 0 0)))

  ;; Overriding the default horizontal split
  (setq split-height-threshold nil)
  (setq split-width-threshold 0)

  ;; Line Numbers
  (setq display-line-numbers-type 'relative)
  (global-display-line-numbers-mode 1)

  ;; Colorscheme inspired by Solarized
  (custom-set-faces
       '(default ((t (:background "#fdf6e3" :foreground "#2e3440")))))

#+end_src

** org-mode

#+begin_src emacs-lisp

  (setq org-src-fontify-natively t)

  (custom-set-faces
   '(org-block ((t (:background "#e4e7ec" :extend t))))
   '(org-block-begin-line
     ((t (:background "#5e81ac" :foreground "#eceff4" :extend t))))
   '(org-block-end-line
     ((t (:background "#5e81ac" :foreground "#eceff4" :extend t)))))

#+end_src

** Splash screen

#+begin_src emacs-lisp

  ;; (setq inhibit-startup-screen t)
  
#+end_src
